name: ssl-wsi
channels:
  - pytorch
  - nvidia
  - defaults
  - conda-forge
dependencies:
  - python=3.9.*
  - pytorch=2.0.*
  - pytorch-cuda=11.8
  - torchvision=0.15.*
  - pip:
    - albumentations==1.3.*
    - einops==0.7.*
    - jsonargparse==4.21.*
    - lightly==1.4.*
    - lightning==2.0.*
    - opencv-python==4.7.*
    - pandas==1.4.*
    - git+https://github.com/DBO-DKFZ/slide_tools.git
